#!/bin/sh

#colors
c1="\033[1;40;30m"
c2="\033[1;31m"
c3="\033[1;32m"
c4="\033[1;33m"
c5="\033[1;34m"
c6="\033[1;35m"
c7="\033[1;36m"
c8="\033[1;37m"
end="\033[1;0m"

main() { 
  printf "${c2} ██ $( whoami )@$( cat /etc/hostname )${end}\n"
  printf "${c3} ██ Os: $( cat /etc/*release | grep -i pretty_name | awk -F "=" '{print $2}' | sed 's/"//g') $(uname -m)\n"
  printf "${c4} ██ Kernel: $( uname -r )\n"
  printf "${c5} ██ Uptime: $( uptime | awk '{print $3}' | sed 's/,//g' ) \n"
  printf "${c6} ██ Shell: $( echo ${SHELL##*/} )\n"
  printf "${c7} ██ DE/WM: $XDG_CURRENT_DESKTOP\n"
  printf "${c8} ██ Memory: $(free -m | awk '(NR==2){ print $2 - $7 "Mib"}') / $(free -m | awk '(NR==2){print $2}')Mib\n"
  printf "\n"
}

main
